<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>ffximacro</AssemblyName>
    <RootNamespace>FfxiMacros.Cli</RootNamespace>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FfxiMacros.Core\FfxiMacros.Core.csproj" />
  </ItemGroup>

</Project>
